name = "shg-quiz-worker"
main = "shg-quiz-worker.js"
compatibility_date = "2024-01-01"
account_id = "28963e29ce046d75be64994ba4fb8b1d"

[[d1_databases]]
binding = "DB"
database_name = "shg-database"
database_id = "e02632fe-b709-4bb0-8b8d-ace23795556a"
